### ISSUE TITLE
Broken Links on ODP

### ISSUE THREAD

**Issue by kylekirkby** [Linaro/opendataplane-website#34]
A couple of broken links were found by the link checker on our ODP CI Build. Does anyone know what the correct replacement for these should be?

On this page
https://opendataplane.org/mailing-list/index.html
This link is broken
https://lists.linaro.org/mailman/listinfo/lng-odp-ovs
https://lists.linaro.org/pipermail/lng-odp-ovs/

Many Thanks,

Kyle

**Comment by shovanco** [comment]
@kylekirkby Maxim Uvarov has asked us to remove these links

**Comment by kylekirkby** [comment]
@shovanuk Ok removed in the latest PR - https://github.com/Linaro/opendataplane-website/pull/35
