### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by pcolmer** [Linaro/opendataplane-website#47]
/applications/README.md links to https://git.linaro.org/people/nikhil.agarwal/ossl-odp.git which isn't there any more. This repository is also linked to from _posts/2016-12-09-odp-openssl-upto-20x-performance-improvement-large-packets.markdown.

/faq/README.md links to http://www.tuxradar.com/content/newbies-guide-hacking-linux-kernel which isn't there any more.

**Comment by kylekirkby** [comment]
Any update on this? Need to do some updates to the site for Connect and need these links fixed for builds to pass successfully. Don't want to put the wrong link / remove it if we have a suitable replacement.

**Comment by pcolmer** [comment]
I can restore the ossl-odp.git repo if someone tells me where it needs to be stored. The references on those two pages will then need to be changed appropriately.
